name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential make

    - name: Build project (Makefile)
      run: make clean && make

    - name: Run smoke test (non-interactive)
      run: |
        # Provide minimal input to exit immediately: select option 6 (Exit)
        printf "6\n" | ./maze
